//Inventory type
export const SET_INVENTORY_LIST = "SET_INVENTORY_LIST";
export const DELETE_INVENTORY_ITEM = "DELETE_INVENTORY_ITEM";
export const RESET_INVENTORY_LIST = "RESET_INVENTORY_LIST";
export const ADD_INVENTORY = "ADD_INVENTORY";
export const UPDATE_INVENTORY = "UPDATE_INVENTORY";
